### ISSUE TITLE
The subdirectory "foreign/ffmpeg/" is huge (1GB) doesn't seem very useful

### ISSUE THREAD

**Issue by alyptik** [Lind-Project/Lind-misc#2]
The `foreign/ffmpeg/` (originally `forgin/ffmpeg/`) subdirectory is about 1GB at current and just seems to be sitting there.

Would you guys be opposed to a `git filter-branch` and force push to remove it? It really makes cloning this repository annoying sort of annoying.

**Comment by JustinCappos** [comment]
I don't have a problem with this, but what if we moved the apps we've build
with Lind into a separate repo instead?

**Comment by alyptik** [comment]
Sure, that'd be a pretty useful idea. The whole foreign/ directory could be moved somewhere else, along with a few others probably, and just having it just be support utilities/scripts sounds like the best way to go in my opinion.

It's might take me a little while to get to though, but I'm definitely all for it; mostly just wanted to get this particular directory out because it is slowing my Docker/Travis builds down by a very noticeable amount.

**Comment by alyptik** [comment]
Resolved.

**Comment by alyptik** [comment]
The refactoring issue is somewhat orthogonal to the original problem of the huge, random files slowing down clones and the reorganizing will be handled in a future PR/Issue.
